version: 0.1

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - aws s3 sync . s3://$S3_BUCKET
  post_build:
    commands:
      - echo Build completed on `date`
